apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-api
  labels:
    app: random-api
    rel: stable
spec:
  selector:
    matchLabels:
      app: random-api
  replicas: 3
  template:
    metadata:
      labels:
        app: random-api
    spec:
      containers:
        - name: random-api
          image: ttmunyunguma/random-api:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: random-api
spec:
  selector:
    app: random-api
  type: LoadBalancer

  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31111
      protocol: TCP

